### ISSUE TITLE
If a new master is elected, the cluster level RCAs don't execute on the new master

### ISSUE THREAD

**Issue by yojs** [opendistro-for-elasticsearch/performance-analyzer-rca#421]

**Comment by gkamat** [comment]
When a cluster is instanced, the rca*.conf files are properly set up with the locus tags set to "data-node", "master-node" and "idle-master-node" correctly.  When a master node is terminated, one of the backup masters takes over as expected.  But as part of the switch, it appears the locus tags on that backup master get rewritten.  All three files get set to the "idle-master-node" locus.  Consequently, the RCAs that are supposed to run on the master node don't get executed, since the tags don't match.  In fact, no RCA's get executed on this node, since the tag indicatres it is a backup master, not a master node or data node.
